### ISSUE TITLE
Memory utilization spikes after upgrading

### ISSUE THREAD

**Issue by antch22** [splitio/split-evaluator#145] opened 2023-05-10 18:38 UTC
After upgrading to version 2.3.0 from 2.2.0 of the split evaluator container for some testing we're seeing several spikes in memory utilization that didn't exist in 2.2.0.  The spikes would peak between 40% - 80% utilization whereas 2.2.0 did not have such dramatic spikes in usage and typically kept at a consistent 10% - 15% utilization.  As a note our containers run with 2 GB of memory.  Just curious if this is expected behavior or if there are any possible known issues with 2.3.0.

**Comment by agustinona** [comment] 2023-05-10 19:37
Hi @antch22 , there are no known issues in 2.3.0. Could you share the Evaluator config you are running as well as the workload conditions for me to attempt to reproduce this?

**Comment by antch22** [comment] 2023-05-10 20:42
Sure, here's our config:

SPLIT_EVALUATOR_IP_ADDRESSES_ENABLED = true
SPLIT_EVALUATOR_EVENTS_POST_RATE = 30
SPLIT_EVALUATOR_SERVER_PORT = 80
SPLIT_EVALUATOR_LOG_LEVEL = debug
SPLIT_EVALUATOR_SEGMENTS_REFRESH_RATE = 30
SPLIT_EVALUATOR_SPLITS_REFRESH_RATE = 5
SPLIT_EVALUATOR_IMPRESSIONS_POST_RATE = 30
SPLIT_EVALUATOR_EVENTS_QUEUE_SIZE = 300
SPLIT_EVALUATOR_METRICS_POST_RATE = 30

As for our workload, we have an average of about 500 requests per minute.

**Comment by chillaq** [comment] 2024-06-17 18:17
Hi @antch22, Apologies for the late reply, could you please check if you see the same spikes in latest version (2.6.0)?

Thanks
Bilal

**Comment by chillaq** [comment] 2024-06-28 20:09
Hi @antch22 , 

I'm following up on this issue. Do you still require any assistance?

Best,
Bilal

**Comment by chillaq** [comment] 2024-07-03 18:50
Hi @antch22 ,

It has been a while since we heard back from you.
I'm closing out this ticket. If there's still an open issue or if we can be of further assistance on this topic, feel free to respond to re-open it.

Best,
Bilal

**Closed by chillaq** 2024-07-03 18:50 UTC
